version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: delphi-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - delphi-lightrag-network

  # LightRAG API Server
  lightrag:
    image: ghcr.io/hkuds/lightrag:latest
    container_name: delphi-lightrag
    ports:
      - "8080:9621"  # API port
      - "3000:3000"  # Web UI port
    volumes:
      - ./lightrag_storage:/app/lightrag_storage
      - ./.env:/app/.env:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_EMBEDDING_API_BASE=${OPENAI_EMBEDDING_API_BASE:-https://api.openai.com/v1}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-large}
      - EMBEDDING_DIM=3072
      - LLM_BINDING=openai
      - EMBEDDING_BINDING=openai
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION:-delphi_code}
      - LIGHTRAG_WORKING_DIR=/app/lightrag_storage
      - LIGHTRAG_CHUNK_SIZE=${LIGHTRAG_CHUNK_SIZE:-1200}
      - LIGHTRAG_CHUNK_OVERLAP=${LIGHTRAG_CHUNK_OVERLAP:-100}
      - LIGHTRAG_MAX_ASYNC=${LIGHTRAG_MAX_ASYNC:-4}
      - LIGHTRAG_MODE=${LIGHTRAG_MODE:-hybrid}
      - LIGHTRAG_LANGUAGE=${LIGHTRAG_LANGUAGE:-English}
    depends_on:
      - qdrant
    networks:
      - delphi-lightrag-network

networks:
  delphi-lightrag-network:
    driver: bridge